name: Build Rust Project

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Cross build Linux binaries
        if: matrix.os == 'ubuntu-latest'
        uses: zijiren233/cargo-cross@v1
        with:
          command: build
          profile: release
          targets: x86_64-unknown-linux-gnu
          glibc-version: "2.39"
          args: --bins
      - name: Build Windows binaries
        if: matrix.os == 'windows-latest'
        run: cargo build --release --bins
      - name: Run tests
        run: cargo test --release --all-targets
      - name: Upload Linux build artifacts
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v7
        with:
          name: spider-cloud-rs-x86_64-unknown-linux-gnu-glibc-2.39
          path: |
            target/x86_64-unknown-linux-gnu/release/backup-to-cloud
            target/x86_64-unknown-linux-gnu/release/cfmmc-crawler-rs
            target/x86_64-unknown-linux-gnu/release/cloud-uploader-rs
          retention-days: 7
      - name: Upload Windows build artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v7
        with:
          name: spider-cloud-rs-windows-latest
          path: |
            target/release/backup-to-cloud.exe
            target/release/cfmmc-crawler-rs.exe
            target/release/cloud-uploader-rs.exe
          retention-days: 7
    
